import type { Metadata } from "next";
import { Geist, Geist_Mono, } from "next/font/google";
import "./globals.css";
import { ChildProps } from "@/types";
import RootLayoutClient from "@/components/provider/root-provider";
import NextTopLoader from 'nextjs-toploader';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DachaOL",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: ChildProps) {


  return (
    <html lang='en' suppressHydrationWarning={true}>
      <body cz-shortcut-listen="true"
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <RootLayoutClient>
          <NextTopLoader showSpinner={false} />
          {children}
        </RootLayoutClient>
      </body>
    </html>
  );
}

