import type { Metadata } from "next";
import { Geist, Geist_Mono, } from "next/font/google";
import "./globals.css";
import { ChildProps } from "@/types";
import RootLayoutClient from "@/components/provider/root-provider";
import NextTopLoader from 'nextjs-toploader';
import { Toaster } from "@/components/ui/sonner";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DachaOL",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: ChildProps) {


  return (
    <html lang='en' suppressHydrationWarning={true}>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
              m[i].l=1*new Date();
              for (var j = 0; j < document.scripts.length; j++) {if (document.scripts[j].src === r) { return; }}
              k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
              (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

              ym(102649558, "init", {
                clickmap:true,
                trackLinks:true,
                accurateTrackBounce:true,
                webvisor:true,
                ecommerce:"dataLayer"
              });
            `
          }}
        />
      </head>
      <body cz-shortcut-listen="true"
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <RootLayoutClient>
          <NextTopLoader showSpinner={false} />
          {children}
          <Toaster position="top-center" />
        </RootLayoutClient>
        <noscript>
          <div>
            <Image src="https://mc.yandex.ru/watch/102649558"
              style={{ position: 'absolute', left: '-9999px' }}
              alt="yandex metirka"
              width={250}
              height={150}
            />
          </div>
        </noscript>
      </body>
    </html>
  );
}

