import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { appWithTranslation } from 'next-i18next';
import "./globals.css";
import { ChildProps } from "@/types";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayout({ children }: ChildProps) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body cz-shortcut-listen="true"
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <RootLayout>
          {children}
        </RootLayout>
      </body>
    </html>
  );
}

export default appWithTranslation(RootLayout);