export const QUERY_KEYS = {
    cottages: "cottages",
    cottageTop: "CottageTop",
    cottages_by_place: "cottages_by_place",
    cottage_by_filter: "cottage_by_filter",
    cottage_by_UserId: "user_cottage_single",
    cottageType_by_Id: "cottage-taype-by-id",
    cottage_suitable_id: 'cottage_suitable_id',
    cottage_by_id: "cottage_by_id_view",
    languages: "languages",
    places: "places",
    place_by_id: "place_bu_id",
    regions: "regions",
    cottageType: "cottagetypes",
    comforts: "comforts",
    users: "users",
    notification: "notifications",
    all_notification: "all_notification",
    services: "services",
    servicesId: "servicesId",
    tariff: "tariffs",
    cottageUserAllId: "cottageUserIdAll",
    userCottageUser: "UserCottageUser",
    order: "orders",
    cottage_by_isTop: "cottage_top_byId",
    cottage_by_recommended: "cottage_recom_byId",
    commit_key:"commit_keys"
};
